# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.0.10.post1.dev0+g97db033.d20210823'
version_tuple = (0, 0, 10, 'post1', 'dev0+g97db033', 'd20210823')
